### ISSUE TITLE
Instantiate backstack before executing fragment transaction

### ISSUE THREAD

**Issue by daniel-m-dd** [Zhuinden/simple-stack#181]
Hi, 
First of all, thank you for this library.
I was wondering if there is a meaning executing the transaction of the navigation backstack host before instating the backstack?
(=> why not moving this [block](https://github.com/Zhuinden/simple-stack/blob/master/simple-stack/src/main/java/com/zhuinden/simplestack/navigator/Navigator.java#L256) after [that]( https://github.com/Zhuinden/simple-stack/blob/master/simple-stack/src/main/java/com/zhuinden/simplestack/navigator/Navigator.java#L271) )
I am currently initializing the Navigator in a custom view group (not necessarily instantiated in onCreate) and not in the Activity onCreate ; and this result on this crash:
```
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.zhuinden.simplestack.Backstack.reattachStateChanger()' on a null object reference
        at com.zhuinden.simplestack.navigator.BackstackHost.onResume(BackstackHost.java:106)
        at android.app.Fragment.performResume(Fragment.java:2568)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1341)
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1576)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1637)
        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2215)
        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2161)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2062)
        at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:818)
        at com.zhuinden.simplestack.navigator.Navigator.install(Navigator.java:259)
        at com.zhuinden.simplestack.navigator.Navigator.access$000(Navigator.java:51)
        at com.zhuinden.simplestack.navigator.Navigator$Installer.install(Navigator.java:217)
```
Thanks!

**Comment by Zhuinden** [comment]
Hmm, theoretically you shouldn't have a BackstackHost without having called `Navigator.install`. Are you calling `Navigator.install` inside a `if(savedInstanceState == null) {` block? Because Navigator was designed in such a way that it expects you not to (namely it won't reinitialize the backstack within the host if you don't call install). 

If you want a Backstack that is specific to your view, and not for top-level navigation, then I advise using Backstack directly. Navigator intends to be "global and single instance within its host Activity".

**Comment by daniel-m-dd** [comment]
I am calling `Navigator.install` in the constructor of my custom view; the BackStackHost is initialized duing the (first) install but the fragment transaction perform a resume which is crashing since the backstack is not yet initialized (last operation of the install).
I will try with a Backstack directly; thanks.

**Comment by daniel-m-dd** [comment]
Confirming I can make it work by calling the backstack and binding it to my custom view lifecycle.

**Comment by Zhuinden** [comment]
Cool! Don't forget to use `toBundle`/`fromBundle`.
