### ISSUE TITLE
Community sample crash

### ISSUE THREAD

**Issue by omkar-tenkale** [Zhuinden/simple-stack#253]
```

2022-03-10 02:00:10.822 21953-21953/com.community.simplestackkotlindaggerexample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.community.simplestackkotlindaggerexample, PID: 21953
    java.lang.ExceptionInInitializerError
        at okhttp3.internal.platform.Platform.get(Platform.java:85)
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229)
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1015)
        at com.community.simplestackkotlindaggerexample.application.injection.AppModule.okhttpClient(AppModule.kt:54)
        at com.community.simplestackkotlindaggerexample.application.injection.AppModule_OkhttpClientFactory.okhttpClient(AppModule_OkhttpClientFactory.java:37)
        at com.community.simplestackkotlindaggerexample.application.injection.AppModule_OkhttpClientFactory.get(AppModule_OkhttpClientFactory.java:28)
        at com.community.simplestackkotlindaggerexample.application.injection.AppModule_OkhttpClientFactory.get(AppModule_OkhttpClientFactory.java:11)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.community.simplestackkotlindaggerexample.application.injection.AppModule_ApiServiceFactory.get(AppModule_ApiServiceFactory.java:33)
        at com.community.simplestackkotlindaggerexample.application.injection.AppModule_ApiServiceFactory.get(AppModule_ApiServiceFactory.java:12)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.community.simplestackkotlindaggerexample.application.injection.DaggerAppComponent.injectUsersFragment(DaggerAppComponent.java:67)
        at com.community.simplestackkotlindaggerexample.application.injection.DaggerAppComponent.inject(DaggerAppComponent.java:63)
        at com.community.simplestackkotlindaggerexample.screens.users.UsersFragment.onAttach(UsersFragment.kt:40)
        at androidx.fragment.app.Fragment.performAttach(Fragment.java:2954)
        at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:463)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:254)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 30
        at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:238)
        at okhttp3.internal.platform.Platform.findPlatform(Platform.java:202)
        at okhttp3.internal.platform.Platform.<clinit>(Platform.java:79)
        at okhttp3.internal.platform.Platform.get(Platform.java:85) 
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263) 
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229) 
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1015) 
        at com.community.simplestackkotlindaggerexample.application.injection.AppModule.okhttpClient(AppModule.kt:54) 
        at com.community.simplestackkotlindaggerexample.application.injection.AppModule_OkhttpClientFactory.okhttpClient(AppModule_OkhttpClientFactory.java:37) 
        at com.community.simplestackkotlindaggerexample.application.injection.AppModule_OkhttpClientFactory.get(AppModule_OkhttpClientFactory.java:28) 
        at com.community.simplestackkotlindaggerexample.application.injection.AppModule_OkhttpClientFactory.get(AppModule_OkhttpClientFactory.java:11) 
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47) 
        at com.community.simplestackkotlindaggerexample.application.injection.AppModule_ApiServiceFactory.get(AppModule_ApiServiceFactory.java:33) 
        at com.community.simplestackkotlindaggerexample.application.injection.AppModule_ApiServiceFactory.get(AppModule_ApiServiceFactory.java:12) 
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47) 
        at com.community.simplestackkotlindaggerexample.application.injection.DaggerAppComponent.injectUsersFragment(DaggerAppComponent.java:67) 
        at com.community.simplestackkotlindaggerexample.application.injection.DaggerAppComponent.inject(DaggerAppComponent.java:63) 
        at com.community.simplestackkotlindaggerexample.screens.users.UsersFragment.onAttach(UsersFragment.kt:40) 
        at androidx.fragment.app.Fragment.performAttach(Fragment.java:2954) 
        at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:463) 
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:254) 
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840) 
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758) 
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701) 
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

**Comment by Zhuinden** [comment]
oh I've encountered this before in the wild, I guess I need to update some dependencies in some samples (namely OkHttp in this case)
